package com.chabi.android.chabiapp.utils

import com.chabi.android.chabiapp.data.source.local.entity.PersonalityEntity

object PersonalityDataFactory {

    fun generatePersonalityData(): List<PersonalityEntity> {
        val personalities = ArrayList<PersonalityEntity>()

        personalities.add(
            PersonalityEntity(
                1,
                "ISFJ",
                0f,
                "Tenang, Terjadwal, dan Hati-hati",
                "Serius, literal, terampil dan berorientasi pada detail. Paling bahagia dengan jadwal yang andal yang tidak sering berubah dan risiko paling sedikit. Pribadi, namun menikmati menjadi bagian dari komunitas yang lebih luas. Mereka menikmati waktu satu lawan satu dan berkembang dalam penetapan tujuan, aturan, arahan, dan persiapan.",
                "Selamat datang di dunia fakta dan detail pribadi Beaver! Berang-berang memiliki preferensi untuk introvert. Mereka dapat diandalkan, pendiam, dan rajin dengan keterampilan kinerja langkah demi langkah, biasanya berakhir dengan hasil yang sangat baik. Mereka paling bahagia di lingkungan yang terkendali dan terjadwal di mana aturannya dijabarkan secara rinci dan ketika mereka tahu apa yang diharapkan dari mereka. Di luar, Berang-berang biasanya pendiam dan berperilaku baik karena dilihat sebagai \"anak yang baik\" sangat penting bagi mereka. Mereka berusaha untuk melakukan apa yang benar dalam setiap situasi, dan karena itu, Berang-berang dapat menjadi sangat keras pada diri mereka sendiri. Sikap perfeksionis ini dapat menyebabkan kekhawatiran dan kecemasan yang melemahkan, terutama dalam situasi atau hubungan baru. Karena mereka memproses di kepala mereka, itu bisa menjadi tantangan nyata bagi orang lain untuk memahami kedalaman kejadian di otak mereka. Ketika Berang-berang memiliki orang dewasa yang sabar dan suportif yang meluangkan waktu untuk menjelaskan berbagai hal dan membantu mereka memproses apa yang mereka rasakan, mereka bisa menjadi anak-anak yang paling baik, suka menolong, setia, dan pekerja keras yang pernah Anda temui. Perhatian mereka pada detail dikombinasikan dengan ketekunan mereka membuat kombo yang kuat yang secara signifikan dapat membuat dunia menjadi tempat yang lebih baik (dan lebih sistematis).",
                "https://www.youtube.com/watch?v=rkczkn998JI;https://www.youtube.com/watch?v=3G81qlgvPko;https://www.youtube.com/watch?v=HbKf7y150fM&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=89;https://www.youtube.com/watch?v=NMaQJIDuaGM&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=81;https://www.youtube.com/watch?v=WhHS6LIIap0&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh;https://www.youtube.com/watch?v=Ymjd6tLNDzA&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=11;https://www.youtube.com/watch?v=xc5cVyf5w98&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=113;https://www.youtube.com/watch?v=hkilGLQHpgA&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=67",
                "Beaver",
                "image url"
            )
        )

        personalities.add(
            PersonalityEntity(
                2,
                "ISTJ",
                0f,
                "Tenang, Terjadwal, dan Hati-hati",
                "Serius, literal, terampil dan berorientasi pada detail. Paling bahagia dengan jadwal yang andal yang tidak sering berubah dan risiko paling sedikit. Pribadi, namun menikmati menjadi bagian dari komunitas yang lebih luas. Mereka menikmati waktu satu lawan satu dan berkembang dalam penetapan tujuan, aturan, arahan, dan persiapan.",
                "Selamat datang di dunia fakta dan detail pribadi Beaver! Berang-berang memiliki preferensi untuk introvert. Mereka dapat diandalkan, pendiam, dan rajin dengan keterampilan kinerja langkah demi langkah, biasanya berakhir dengan hasil yang sangat baik. Mereka paling bahagia di lingkungan yang terkendali dan terjadwal di mana aturannya dijabarkan secara rinci dan ketika mereka tahu apa yang diharapkan dari mereka. Di luar, Berang-berang biasanya pendiam dan berperilaku baik karena dilihat sebagai \"anak yang baik\" sangat penting bagi mereka. Mereka berusaha untuk melakukan apa yang benar dalam setiap situasi, dan karena itu, Berang-berang dapat menjadi sangat keras pada diri mereka sendiri. Sikap perfeksionis ini dapat menyebabkan kekhawatiran dan kecemasan yang melemahkan, terutama dalam situasi atau hubungan baru. Karena mereka memproses di kepala mereka, itu bisa menjadi tantangan nyata bagi orang lain untuk memahami kedalaman kejadian di otak mereka. Ketika Berang-berang memiliki orang dewasa yang sabar dan suportif yang meluangkan waktu untuk menjelaskan berbagai hal dan membantu mereka memproses apa yang mereka rasakan, mereka bisa menjadi anak-anak yang paling baik, suka menolong, setia, dan pekerja keras yang pernah Anda temui. Perhatian mereka pada detail dikombinasikan dengan ketekunan mereka membuat kombo yang kuat yang secara signifikan dapat membuat dunia menjadi tempat yang lebih baik (dan lebih sistematis).",
                "https://www.youtube.com/watchv=rkczkn998JI;https://www.youtube.com/watch?v=3G81qlgvPko;https://www.youtube.com/watch?v=PVTTJUBLLvQ&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=55;https://www.youtube.com/watch?v=hkilGLQHpgA&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=66;https://www.youtube.com/watch?v=enIDg17LPMM&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=72;https://www.youtube.com/watch?v=kAo4-2UzgPo;https://www.youtube.com/watch?v=eKDbdAZO-F0;https://www.youtube.com/watch?v=Pb059iwcyUA&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=1;https://www.youtube.com/watch?v=iFDlLz50AWE&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=11;https://www.youtube.com/watch?v=ag92tlMNITg&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=41;https://www.youtube.com/watch?v=TE_hwlukfdk&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=59;https://www.youtube.com/watch?v=i1UfefPfa8I&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=64",
                "Beaver",
                "image url"
            )
        )

        personalities.add(
            PersonalityEntity(
                3,
                "INFJ",
                0f,
                "Tenang, Kreatif, dan Imaginatif",
                "Sangat pribadi dengan kebutuhan akan kesendirian yang tenang. Paling bahagia di dunia mereka sendiri menciptakan dan membayangkan apa yang bisa terjadi. Cerdas dan kreatif dengan wawasan dan firasat yang sering kali ternyata benar. Mereka mungkin mengalami banyak momen “ahaa” yang membantu mereka memahami pengalaman mereka. Tipe kuat dan pendiam yang selalu suka membuat Anda tersenyum.",
                "Selamat datang di dunia batin Panda yang sangat pribadi dan kreatif! Panda memiliki preferensi untuk introversi, terus-menerus berpikir dan memiliki bakat alami untuk memahami dan menghubungkan emosi mendalam mereka dengan pengalaman. Karena itu, mereka membutuhkan lebih banyak privasi untuk diproses dibandingkan dengan kebanyakan anak-anak. Mereka paling bahagia di dunia mereka sendiri, menciptakan dan membayangkan apa yang bisa terjadi. Mereka memiliki kekuatan yang tenang dengan tekad yang tenang dan berkembang paling baik di lingkungan yang harmonis dan mendukung. Anak-anak ini menghabiskan sebagian besar waktu mereka untuk berpikir dan biasanya akan berada di tempat lain secara mental. Mereka didorong untuk melihat gambaran besar dan memahami bagaimana segala sesuatunya bekerja pada tingkat akar penyebab yang mendasar. Mereka suka mempelajari teori, konsep, dan sistem baru yang canggih dan cenderung strategis dalam memahaminya. Otak mereka memproses informasi secara berbeda dari kebanyakan orang, mengingat mereka tipe kepribadian langka yang hanya 4% dari populasi anak-anak. Karena itu, mereka mudah disalahpahami. Jadi kami akan membantu Anda mengenal dan mencintai Panda Anda dengan lebih baik. Mari kita mulai dengan bagaimana otak mereka memproses informasi",
                "https://www.youtube.com/watch?v=rkczkn998JI;https://www.youtube.com/watch?v=3G81qlgvPko;https://www.youtube.com/watch?v=kAo4-2UzgPo;https://www.youtube.com/watch?v=eKDbdAZO-F0;https://www.youtube.com/watch?v=Pb059iwcyUA&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=1;https://www.youtube.com/watch?v=iFDlLz50AWE&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=11;https://www.youtube.com/watch?v=ag92tlMNITg&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=41;",
                "Panda",
                "image url"
            )
        )

        personalities.add(
            PersonalityEntity(
                4,
                "INTJ",
                0f,
                "Tenang, Kreatif, dan Imaginatif",
                "Intensely private with a need for quiet solitude. Happiest in their own world creating and imagining what could be. Smart and creative with frequent insights and hunches that tend to turn out correct. They may experience many “ahaa” moments which help them understand their experiences. Strong, quiet types that always love to make you smile. ",
                "Selamat datang di dunia batin Panda yang sangat pribadi dan kreatif! Panda memiliki preferensi untuk introversi, terus-menerus berpikir dan memiliki bakat alami untuk memahami dan menghubungkan emosi mendalam mereka dengan pengalaman. Karena itu, mereka membutuhkan lebih banyak privasi untuk diproses dibandingkan dengan kebanyakan anak-anak. Mereka paling bahagia di dunia mereka sendiri, menciptakan dan membayangkan apa yang bisa terjadi. Mereka memiliki kekuatan yang tenang dengan tekad yang tenang dan berkembang paling baik di lingkungan yang harmonis dan mendukung. Anak-anak ini menghabiskan sebagian besar waktu mereka untuk berpikir dan biasanya akan berada di tempat lain secara mental. Mereka didorong untuk melihat gambaran besar dan memahami bagaimana segala sesuatunya bekerja pada tingkat akar penyebab yang mendasar. Mereka suka mempelajari teori, konsep, dan sistem baru yang canggih dan cenderung strategis dalam memahaminya. Otak mereka memproses informasi secara berbeda dari kebanyakan orang, mengingat mereka tipe kepribadian langka yang hanya 4% dari populasi anak-anak. Karena itu, mereka mudah disalahpahami. Jadi kami akan membantu Anda mengenal dan mencintai Panda Anda dengan lebih baik. Mari kita mulai dengan bagaimana otak mereka memproses informasi",
                "https://www.youtube.com/watch?v=rkczkn998JI;https://www.youtube.com/watch?v=3G81qlgvPko;https://www.youtube.com/watch?v=kAo4-2UzgPo;https://www.youtube.com/watch?v=eKDbdAZO-F0;https://www.youtube.com/watch?v=Pb059iwcyUA&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=1;https://www.youtube.com/watch?v=iFDlLz50AWE&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=11;https://www.youtube.com/watch?v=ag92tlMNITg&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=41;",
                "Panda",
                "image url"
            )
        )

        personalities.add(
            PersonalityEntity(
                5,
                "INFP",
                0f,
                "Moralistis, Lembut dan Sensitif",
                "Paling bahagia dalam lingkungan yang tenang, kooperatif dan mendukung di mana mereka dapat mengejar hal-hal penting. Mereka memiliki sistem kecemasan internal yang alami. Sangat peka terhadap lingkungan mereka",
                "Selamat datang di dunia batin Meerkat yang kompleks dan indah. Meerkat memiliki preferensi untuk introversi. Mereka bermoral, lembut, dan sensitif dengan bakat untuk semua hal yang artistik dan kreatif. Mereka paling bahagia di lingkungan yang tenang, kooperatif, dan mendukung di mana mereka dapat mengejar hal-hal yang bermakna. Di luar, Meerkat tampak sangat pemalu, pendiam, dan pemalu. Namun, ada bagian bawahnya - seluruh dunia perasaan rumit terjadi di balik layar. Mereka cenderung menjadi yang paling sensitif dari semua tipe kepribadian karena mereka cenderung merasa jauh lebih dalam dan mendalam daripada yang lain. Sebagai anak kecil, perasaan besar ini terkadang dapat melemahkan Meerkat karena mereka melakukan yang terbaik untuk menyelesaikan semua yang terjadi di dalam. Karena mereka biasanya sangat tertutup, ini bisa menjadi tantangan nyata bagi orang lain untuk memahami kedalaman dari semua yang terjadi di balik ketenangan mereka. Namun, ketika diberi waktu tenang yang cukup untuk berefleksi bersama dengan lingkungan yang damai dan harmonis, Meerkat dapat menjadi penolong yang paling bijaksana dan luar biasa. Hati mereka yang besar, bercampur dengan kreativitas mereka, membuat kombo yang kuat yang secara signifikan dapat membantu orang lain dan membuat dunia menjadi tempat yang lebih baik (dan lebih indah).",
                "https://www.youtube.com/watch?v=rkczkn998JI;https://www.youtube.com/watch?v=3G81qlgvPko;https://www.youtube.com/watch?v=FgdKD9owv7E&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=7;https://www.youtube.com/watch?v=iFDlLz50AWE&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=12;https://www.youtube.com/watch?v=i1UfefPfa8I&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=65;https://www.youtube.com/watch?v=kAo4-2UzgPo;https://www.youtube.com/watch?v=eKDbdAZO-F0;https://www.youtube.com/watch?v=Pb059iwcyUA&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=1;https://www.youtube.com/watch?v=iFDlLz50AWE&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=11;https://www.youtube.com/watch?v=ag92tlMNITg&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=41;https://www.youtube.com/watch?v=W8QZCb0ol2Y&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=9;",
                "Meerkat",
                "image url"
            )
        )

        personalities.add(
            PersonalityEntity(
                6,
                "ISFP",
                0f,
                "Moralistis, Lembut dan Sensitif",
                "Paling bahagia dalam lingkungan yang tenang, kooperatif dan mendukung di mana mereka dapat mengejar hal-hal penting. Mereka memiliki sistem kecemasan internal yang alami. Sangat peka terhadap lingkungan mereka",
                "Selamat datang di dunia batin Meerkat yang kompleks dan indah. Meerkat memiliki preferensi untuk introversi. Mereka bermoral, lembut, dan sensitif dengan bakat untuk semua hal yang artistik dan kreatif. Mereka paling bahagia di lingkungan yang tenang, kooperatif, dan mendukung di mana mereka dapat mengejar hal-hal yang bermakna. Di luar, Meerkat tampak sangat pemalu, pendiam, dan pemalu. Namun, ada bagian bawahnya - seluruh dunia perasaan rumit terjadi di balik layar. Mereka cenderung menjadi yang paling sensitif dari semua tipe kepribadian karena mereka cenderung merasa jauh lebih dalam dan mendalam daripada yang lain. Sebagai anak kecil, perasaan besar ini terkadang dapat melemahkan Meerkat karena mereka melakukan yang terbaik untuk menyelesaikan semua yang terjadi di dalam. Karena mereka biasanya sangat tertutup, ini bisa menjadi tantangan nyata bagi orang lain untuk memahami kedalaman dari semua yang terjadi di balik ketenangan mereka. Namun, ketika diberi waktu tenang yang cukup untuk berefleksi bersama dengan lingkungan yang damai dan harmonis, Meerkat dapat menjadi penolong yang paling bijaksana dan luar biasa. Hati mereka yang besar, bercampur dengan kreativitas mereka, membuat kombo yang kuat yang secara signifikan dapat membantu orang lain dan membuat dunia menjadi tempat yang lebih baik (dan lebih indah).",
                "https://www.youtube.com/watch?v=rkczkn998JI;https://www.youtube.com/watch?v=3G81qlgvPko;https://www.youtube.com/watch?v=THAIfa8EXgA&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=54;https://www.youtube.com/watch?v=2Oazci7VrNU&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=4;https://www.youtube.com/watch?v=KbiskP6M5P8&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=13;https://www.youtube.com/watch?v=mF-2ihX6lFU&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=19",
                "Meerkat",
                "image url"
            )
        )

        personalities.add(
            PersonalityEntity(
                7,
                "INTP",
                0f,
                "Tenang, Logis dan Ingin Tahu",
                "Paling bahagia di lingkungan yang tidak terstruktur di mana mereka bebas berpikir dan bermain-main. Fokus mereka adalah menganalisis dan memecahkan masalah kompleks dengan cara yang tidak biasa. Mereka cenderung tenang dan santai karena kebutuhan mereka mudah ditentukan. Namun, mereka tidak suka diberi tahu apa yang harus dilakukan dan juga tidak ingin memberi tahu orang lain apa yang harus dilakukan. Bijaksana dan sangat kompeten dengan kemampuan untuk beradaptasi dengan sebagian besar situasi.",
                "Selamat datang di dunia batin burung hantu yang sistematis dan analitis. Burung hantu memiliki preferensi untuk introversi dan lebih menikmati dunia batin mereka daripada ditemani anak-anak lain. Mereka bijaksana, kompeten, dan biasanya santai dengan kemampuan memecahkan masalah kompleks dengan cara yang tidak biasa. Mereka paling bahagia di lingkungan yang tidak terstruktur di mana mereka bebas untuk berpikir, mengotak-atik, dan mencari tahu bagaimana segala sesuatunya bekerja. Burung hantu cenderung menjadi pengamat yang pendiam yang puas dengan melihat orang atau aktivitas tetapi tidak selalu berpartisipasi kecuali diundang. Mereka tenang dan pendiam, bahkan selama krisis — ini adalah anak-anak yang tetap berkepala dingin dan banyak akal ketika emosi orang lain sedang tinggi. Mereka dapat beradaptasi dengan sebagian besar situasi dengan mudah karena kebutuhan mereka mudah ditentukan. Mereka benci diberi tahu apa yang harus dilakukan dan juga tidak ingin memberi tahu orang lain apa yang harus dilakukan.\n" +
                        "\n" +
                        "Dengan dunia yang penuh dengan pertanyaan, tujuan hidup mereka adalah mencari tahu segala sesuatunya sejujur \u200B\u200Bdan seakurat mungkin. Mereka cenderung menantang status quo, opini, dan/atau keyakinan orang dewasa, tidak peduli seberapa penting orang tersebut. Mereka cepat menemukan ketidakkonsistenan dalam percakapan dan menerima kritik atau ketidaksepakatan, menganggapnya konstruktif daripada pribadi. Termotivasi oleh nalar dan logika daripada perasaan, mereka cenderung tetap terpisah secara objektif melalui diskusi apa pun. Akibatnya, Burung Hantu tanpa sadar dapat menyinggung perasaan orang lain dengan kritik keras mereka dan dapat terlihat tidak peduli. Sangat membantu bagi orang dewasa untuk memahami bahwa analisis kritis mereka tentang dunia adalah sarana untuk memahami dan meningkatkan berbagai hal, dan mereka tidak bermaksud jahat atau kasar. Otak mereka secara alami analitis, logis, dan objektif. Mungkin sulit bagi orang lain untuk memahami kedalaman semua yang terjadi di balik ketenangan mereka. Namun, ketika diberikan lingkungan yang tepat, anak-anak ini berkembang pesat. Mereka menginginkan ketidaksesuaian, waktu tenang yang cukup, kemandirian, dan kebebasan untuk mengotak-atik apa pun yang mereka renungkan. Keingintahuan mereka tentang bagaimana segala sesuatu bekerja bercampur dengan analisis kritis mereka adalah kombinasi kuat yang dapat memecahkan banyak masalah dan menjadikan dunia tempat yang lebih baik (dan lebih fungsional).",
                "https://www.youtube.com/watch?v=rkczkn998JI;https://www.youtube.com/watch?v=3G81qlgvPko;https://www.youtube.com/watch?v=kAo4-2UzgPo;https://www.youtube.com/watch?v=eKDbdAZO-F0;https://www.youtube.com/watch?v=Pb059iwcyUA&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=1;https://www.youtube.com/watch?v=iFDlLz50AWE&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=11;https://www.youtube.com/watch?v=ag92tlMNITg&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=41;https://www.youtube.com/watch?v=CSo0NazM6XI&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=17;https://www.youtube.com/watch?v=k-OfuX72ww0;https://www.youtube.com/watch?v=bhlUJvj7sZw&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=16;https://www.youtube.com/watch?v=NK0ojZTsKxw&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=29;https://www.youtube.com/watch?v=0MANp5bqy7w&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=33",
                "Owl",
                "image url"
            )
        )

        personalities.add(
            PersonalityEntity(
                8,
                "ISTP",
                0f,
                "Tenang, Logis dan Ingin Tahu",
                "Paling bahagia di lingkungan yang tidak terstruktur di mana mereka bebas berpikir dan bermain-main. Fokus mereka adalah menganalisis dan memecahkan masalah kompleks dengan cara yang tidak biasa. Mereka cenderung tenang dan santai karena kebutuhan mereka mudah ditentukan. Namun, mereka tidak suka diberi tahu apa yang harus dilakukan dan juga tidak ingin memberi tahu orang lain apa yang harus dilakukan. Bijaksana dan sangat kompeten dengan kemampuan untuk beradaptasi dengan sebagian besar situasi.",
                "Selamat datang di dunia batin burung hantu yang sistematis dan analitis. Burung hantu memiliki preferensi untuk introversi dan lebih menikmati dunia batin mereka daripada ditemani anak-anak lain. Mereka bijaksana, kompeten, dan biasanya santai dengan kemampuan memecahkan masalah kompleks dengan cara yang tidak biasa. Mereka paling bahagia di lingkungan yang tidak terstruktur di mana mereka bebas untuk berpikir, mengotak-atik, dan mencari tahu bagaimana segala sesuatunya bekerja. Burung hantu cenderung menjadi pengamat yang pendiam yang puas dengan melihat orang atau aktivitas tetapi tidak selalu berpartisipasi kecuali diundang. Mereka tenang dan pendiam, bahkan selama krisis — ini adalah anak-anak yang tetap berkepala dingin dan banyak akal ketika emosi orang lain sedang tinggi. Mereka dapat beradaptasi dengan sebagian besar situasi dengan mudah karena kebutuhan mereka mudah ditentukan. Mereka benci diberi tahu apa yang harus dilakukan dan juga tidak ingin memberi tahu orang lain apa yang harus dilakukan.\n" +
                        "\n" +
                        "Dengan dunia yang penuh dengan pertanyaan, tujuan hidup mereka adalah mencari tahu segala sesuatunya sejujur \u200B\u200Bdan seakurat mungkin. Mereka cenderung menantang status quo, opini, dan/atau keyakinan orang dewasa, tidak peduli seberapa penting orang tersebut. Mereka cepat menemukan ketidakkonsistenan dalam percakapan dan menerima kritik atau ketidaksepakatan, menganggapnya konstruktif daripada pribadi. Termotivasi oleh nalar dan logika daripada perasaan, mereka cenderung tetap terpisah secara objektif melalui diskusi apa pun. Akibatnya, Burung Hantu tanpa sadar dapat menyinggung perasaan orang lain dengan kritik keras mereka dan dapat terlihat tidak peduli. Sangat membantu bagi orang dewasa untuk memahami bahwa analisis kritis mereka tentang dunia adalah sarana untuk memahami dan meningkatkan berbagai hal, dan mereka tidak bermaksud jahat atau kasar. Otak mereka secara alami analitis, logis, dan objektif. Mungkin sulit bagi orang lain untuk memahami kedalaman semua yang terjadi di balik ketenangan mereka. Namun, ketika diberikan lingkungan yang tepat, anak-anak ini berkembang pesat. Mereka menginginkan ketidaksesuaian, waktu tenang yang cukup, kemandirian, dan kebebasan untuk mengotak-atik apa pun yang mereka renungkan. Keingintahuan mereka tentang bagaimana segala sesuatu bekerja bercampur dengan analisis kritis mereka adalah kombinasi kuat yang dapat memecahkan banyak masalah dan menjadikan dunia tempat yang lebih baik (dan lebih fungsional).",
                "https://www.youtube.com/watch?v=rkczkn998JI;https://www.youtube.com/watch?v=3G81qlgvPko;https://www.youtube.com/watch?v=PVTTJUBLLvQ&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=55;https://www.youtube.com/watch?v=hkilGLQHpgA&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=66;https://www.youtube.com/watch?v=enIDg17LPMM&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=72;https://www.youtube.com/watch?v=kAo4-2UzgPo;https://www.youtube.com/watch?v=eKDbdAZO-F0;https://www.youtube.com/watch?v=Pb059iwcyUA&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=1;https://www.youtube.com/watch?v=iFDlLz50AWE&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=11;https://www.youtube.com/watch?v=ag92tlMNITg&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=41;https://www.youtube.com/watch?v=W8QZCb0ol2Y&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=9;https://www.youtube.com/watch?v=rkczkn998JI;https://www.youtube.com/watch?v=3G81qlgvPko;https://www.youtube.com/watch?v=THAIfa8EXgA&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=54;https://www.youtube.com/watch?v=2Oazci7VrNU&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=4;https://www.youtube.com/watch?v=KbiskP6M5P8&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=13;https://www.youtube.com/watch?v=mF-2ihX6lFU&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=19",
                "Owl",
                "image url"
            )
        )

        personalities.add(
            PersonalityEntity(
                9,
                "ESFP",
                0f,
                "Menyenangkan, Petualangan dan Penuh Energi",
                "Paling bahagia di lingkungan yang tidak terstruktur di mana mereka bebas berpikir dan bermain-main. Fokus mereka adalah menganalisis dan memecahkan masalah kompleks dengan cara yang tidak biasa. Mereka cenderung tenang dan santai karena kebutuhan mereka mudah ditentukan. Namun, mereka tidak suka diberi tahu apa yang harus dilakukan dan juga tidak ingin memberi tahu orang lain apa yang harus dilakukan. Bijaksana dan sangat kompeten dengan kemampuan untuk beradaptasi dengan sebagian besar situasi.",
                "Sabuk pengaman! Selamat datang di dunia Otter yang sibuk, menyenangkan, dan ribut! Ini seperti Mr. Toad's Wild Ride membesarkan anak ini.\n" +
                        "\n" +
                        "Berang-berang adalah ekstrovert dengan banyak energi dan percikan pizzazz. Sosialisasi yang aktif dan menarik sangat penting karena mereka menjalani kehidupan secara langsung dan selalu siap berpesta!\n" +
                        "\n" +
                        "Mereka cerdas, ramah, dan percaya diri dengan siapa mereka — selalu siap untuk mendapat sorotan dan kesempatan untuk memamerkan bakat mereka. Mereka paling bahagia ketika melakukan aktivitas dengan orang lain, yang membantu mereka berteman dengan mudah.\n" +
                        "\n" +
                        "Anak-anak berang-berang benar-benar ingin tahu tentang kehidupan dan mengalaminya secara langsung. Mereka lebih suka berada di luar menikmati alam atau bermain olahraga daripada duduk di dalam kelas. Mereka merasa sulit untuk duduk diam karena energi mereka yang tinggi dan kebutuhan akan pengalaman kehidupan nyata — eksplorasi, observasi, dan membicarakannya. Mereka selalu dalam perjalanan dan siap untuk berpetualang. (Berang-berang adalah anak-anak yang memberikan serangan panik kepada orang dewasa karena keingintahuan dan kemauan mereka untuk mengambil risiko. Orang dewasa hampir harus berada dua langkah di depan mereka!)\n" +
                        "\n" +
                        "Dunia mereka riang dan spontan. Ingin melakukan perjalanan dadakan? Anak ini sudah siap! Berang-berang menikmati kejutan dan mengubah rencana pada menit terakhir. Karena mereka hidup pada saat ini, mereka membutuhkan pengarahan ulang yang konstan dan pengingat akan aturan, batasan, dan harapan. Jika sesuatu memicu rasa ingin tahu mereka, mereka tidak perlu memikirkan implikasi atau konsekuensi dari tindakan mereka. Keingintahuan mereka seperti, \"Saya ingin tahu bagaimana rasanya menyentuh api?\" dan kemudian tangan mereka segera mendukung rasa ingin tahu itu dengan mengatakan sesuatu seperti, “Saya tidak tahu, tapi kedengarannya sangat luar biasa! Ayo cari tahu!”\n" +
                        "\n" +
                        "Anak-anak berang-berang berkembang pesat ketika diberi tujuan, pekerjaan, atau tanggung jawab yang mereka pedulikan dan menjadi milik mereka. Mereka membutuhkan orang dewasa yang tahu bagaimana menyalurkan energi tinggi mereka tanpa menekan semangat ceria mereka. Kecintaan mereka terhadap orang-orang dan pengalaman kehidupan nyata, bercampur dengan kepercayaan diri mereka, membuat kombo yang kuat yang secara signifikan dapat membuat dunia menjadi tempat yang lebih baik (dan lebih menyenangkan!).",
                "https://www.youtube.com/watch?v=rkczkn998JI;https://www.youtube.com/watch?v=3G81qlgvPko;https://www.youtube.com/watch?v=RkNdYAP5mwg&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=30;https://www.youtube.com/watch?v=64fLmIWHtT4&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=31;https://www.youtube.com/watch?v=LsvrcD_BMqU&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=70",
                "Otter",
                "image url"
            )
        )

        personalities.add(
            PersonalityEntity(
                10,
                "ESTP",
                0f,
                "Menyenangkan, Petualangan dan Penuh Energi",
                "Paling bahagia di lingkungan yang tidak terstruktur di mana mereka bebas berpikir dan bermain-main. Fokus mereka adalah menganalisis dan memecahkan masalah kompleks dengan cara yang tidak biasa. Mereka cenderung tenang dan santai karena kebutuhan mereka mudah ditentukan. Namun, mereka tidak suka diberi tahu apa yang harus dilakukan dan juga tidak ingin memberi tahu orang lain apa yang harus dilakukan. Bijaksana dan sangat kompeten dengan kemampuan untuk beradaptasi dengan sebagian besar situasi.",
                "Sabuk pengaman! Selamat datang di dunia Otter yang sibuk, menyenangkan, dan ribut! Ini seperti Mr. Toad's Wild Ride membesarkan anak ini.\n" +
                        "\n" +
                        "Berang-berang adalah ekstrovert dengan banyak energi dan percikan pizzazz. Sosialisasi yang aktif dan menarik sangat penting karena mereka menjalani kehidupan secara langsung dan selalu siap berpesta!\n" +
                        "\n" +
                        "Mereka cerdas, ramah, dan percaya diri dengan siapa mereka — selalu siap untuk mendapat sorotan dan kesempatan untuk memamerkan bakat mereka. Mereka paling bahagia ketika melakukan aktivitas dengan orang lain, yang membantu mereka berteman dengan mudah.\n" +
                        "\n" +
                        "Anak-anak berang-berang benar-benar ingin tahu tentang kehidupan dan mengalaminya secara langsung. Mereka lebih suka berada di luar menikmati alam atau bermain olahraga daripada duduk di dalam kelas. Mereka merasa sulit untuk duduk diam karena energi mereka yang tinggi dan kebutuhan akan pengalaman kehidupan nyata — eksplorasi, observasi, dan membicarakannya. Mereka selalu dalam perjalanan dan siap untuk berpetualang. (Berang-berang adalah anak-anak yang memberikan serangan panik kepada orang dewasa karena keingintahuan dan kemauan mereka untuk mengambil risiko. Orang dewasa hampir harus berada dua langkah di depan mereka!)\n" +
                        "\n" +
                        "Dunia mereka riang dan spontan. Ingin melakukan perjalanan dadakan? Anak ini sudah siap! Berang-berang menikmati kejutan dan mengubah rencana pada menit terakhir. Karena mereka hidup pada saat ini, mereka membutuhkan pengarahan ulang yang konstan dan pengingat akan aturan, batasan, dan harapan. Jika sesuatu memicu rasa ingin tahu mereka, mereka tidak perlu memikirkan implikasi atau konsekuensi dari tindakan mereka. Keingintahuan mereka seperti, \"Saya ingin tahu bagaimana rasanya menyentuh api?\" dan kemudian tangan mereka segera mendukung rasa ingin tahu itu dengan mengatakan sesuatu seperti, “Saya tidak tahu, tapi kedengarannya sangat luar biasa! Ayo cari tahu!”\n" +
                        "\n" +
                        "Anak-anak berang-berang berkembang pesat ketika diberi tujuan, pekerjaan, atau tanggung jawab yang mereka pedulikan dan menjadi milik mereka. Mereka membutuhkan orang dewasa yang tahu bagaimana menyalurkan energi tinggi mereka tanpa menekan semangat ceria mereka. Kecintaan mereka terhadap orang-orang dan pengalaman kehidupan nyata, bercampur dengan kepercayaan diri mereka, membuat kombo yang kuat yang secara signifikan dapat membuat dunia menjadi tempat yang lebih baik (dan lebih menyenangkan!).",
                "https://www.youtube.com/watch?v=rkczkn998JI;https://www.youtube.com/watch?v=3G81qlgvPko;https://www.youtube.com/watch?v=kAo4-2UzgPo;https://www.youtube.com/watch?v=eKDbdAZO-F0;https://www.youtube.com/watch?v=Pb059iwcyUA&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=1;https://www.youtube.com/watch?v=iFDlLz50AWE&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=11;https://www.youtube.com/watch?v=ag92tlMNITg&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=41;https://www.youtube.com/watch?v=bhlUJvj7sZw&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=16;https://www.youtube.com/watch?v=NK0ojZTsKxw&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=29;https://www.youtube.com/watch?v=0MANp5bqy7w&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=33;https://www.youtube.com/watch?v=rkczkn998JI",
                "Otter",
                "image url"
            )
        )

        personalities.add(
            PersonalityEntity(
                11,
                "ESTJ",
                0f,
                "Logis, Bertekad dan Terlahir Untuk Memimpin",
                "Pemimpin yang loyal, tegas, dan kompeten. Collie adalah kata Gaelik Skotlandia untuk \"berguna\" dan itu benar untuk anak-anak ini! Paling bahagia saat bertanding atau bertugas. Bangga pada kecerdasan mereka dan ingin orang lain mengenali ini juga",
                "Selamat datang di dunia Border Collie yang didorong, kompetitif, dan logis! Mereka adalah ekstrovert yang suka berbicara dan merupakan pemimpin alami. Mereka ingin bertanggung jawab dan mengubah segalanya menjadi kompetisi. Sejak usia sangat muda, mereka didorong oleh tujuan dalam setiap aspek kehidupan mereka, seperti akademis, olahraga, dan hobi. Dengan standar tinggi untuk menghasilkan hasil, anak-anak ini tidak memiliki masalah untuk memimpin dengan menuntut kekuatan dan kontrol. Prestasi adalah tongkat pengukur untuk Border Collies, memberi mereka kegembiraan dan kepuasan. Mereka sangat kompeten dan menginginkan pengaruh dalam segala situasi untuk memastikan segala sesuatunya dilakukan dengan benar. Sikap saya-bisa-melakukan-apa saja-saya-menetapkan-pikiran-saya-untuk-melakukan tampaknya dibangun di dalamnya.\n" +
                        "\n" +
                        "Termotivasi oleh alasan dan logika daripada perasaan, Border Collies berorientasi pada fakta. Mereka cenderung tetap tidak terikat secara objektif, bahkan di tengah situasi yang penuh tekanan. Border Collies sangat percaya diri dengan sikap menang dengan segala cara. Mereka adalah orang-orang yang berprestasi di hampir semua bidang, bermotivasi tinggi dan secara alami kompetitif, baik dengan orang lain maupun untuk memperbaiki rekor mereka sendiri. Mereka menikmati tantangan dan tidak pernah puas dengan yang kurang dari yang terbaik. Sangat terorganisir, analitis, dan sistematis, mereka lebih suka aturan yang masuk akal, dan mereka menghargai komunikasi yang jelas, yang membantu mereka mematuhinya. Jika mereka tidak setuju atau memahami aturan, mereka cenderung menantang orang dewasa yang menetapkan aturan. Mereka paling bahagia saat memimpin dan mengatur kelompok sebaya mereka untuk menghasilkan hasil.\n" +
                        "\n" +
                        "Anak-anak Border Collie akan menjadi pemimpin dan membutuhkan orang dewasa yang sabar yang akan membantu mereka mengembangkan kualitas kepemimpinan yang efektif. Mereka sangat puas menjadi pemimpin dan kemungkinan besar akan berada di posisi kepemimpinan untuk semua atau sebagian dari kehidupan mereka. Pengorganisasian datang secara alami kepada mereka, dan mereka adalah delegator yang sangat baik. Border Collies akan mendelegasikan, mengatur, dan mengekspresikan kemampuan kepemimpinan mereka dalam konteks keluarga. Apa tempat yang bagus untuk belajar! Namun, ketika mereka melampaui batas, beri tahu mereka. Mereka membutuhkan orang dewasa yang akan menetapkan batasan dan menyalurkan energi mereka. Border Collies akan menghormati dan senang bekerja di bawah otoritas selama mereka tahu dan mengerti apa yang diperbolehkan dan apa yang tidak diperbolehkan. Sikap Border Collies yang menyenangkan dan suka berteman bercampur dengan rasa tanggung jawab mereka membuat kombo yang kuat yang dapat secara signifikan meningkatkan dan memajukan dunia.",
                "https://www.youtube.com/watch?v=rkczkn998JI;https://www.youtube.com/watch?v=3G81qlgvPko;https://www.youtube.com/watch?v=PVTTJUBLLvQ&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=55;https://www.youtube.com/watch?v=hkilGLQHpgA&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=66;https://www.youtube.com/watch?v=enIDg17LPMM&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=72;https://www.youtube.com/watch?v=xZd3F9WQz48&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=53;https://www.youtube.com/watch?v=zCkOocQGtDU&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=73;https://www.youtube.com/watch?v=eKDbdAZO-F0;https://www.youtube.com/watch?v=CSo0NazM6XI&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=17;https://www.youtube.com/watch?v=Naui0ZG-Nsc&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=61;https://www.youtube.com/watch?v=k-OfuX72ww0;https://www.youtube.com/watch?v=kAo4-2UzgPo;https://www.youtube.com/watch?v=eKDbdAZO-F0;https://www.youtube.com/watch?v=Pb059iwcyUA&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=1;https://www.youtube.com/watch?v=iFDlLz50AWE&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=11;https://www.youtube.com/watch?v=ag92tlMNITg&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=41",
                "Border Collie",
                "image url"
            )
        )

        personalities.add(
            PersonalityEntity(
                12,
                "ENTJ",
                0f,
                "Logis, Bertekad dan Terlahir Untuk Memimpin",
                "Pemimpin yang loyal, tegas, dan kompeten. Collie adalah kata Gaelik Skotlandia untuk \"berguna\" dan itu benar untuk anak-anak ini! Paling bahagia saat bertanding atau bertugas. Bangga pada kecerdasan mereka dan ingin orang lain mengenali ini juga",
                "Selamat datang di dunia Border Collie yang didorong, kompetitif, dan logis! Mereka adalah ekstrovert yang suka berbicara dan merupakan pemimpin alami. Mereka ingin bertanggung jawab dan mengubah segalanya menjadi kompetisi. Sejak usia sangat muda, mereka didorong oleh tujuan dalam setiap aspek kehidupan mereka, seperti akademis, olahraga, dan hobi. Dengan standar tinggi untuk menghasilkan hasil, anak-anak ini tidak memiliki masalah untuk memimpin dengan menuntut kekuatan dan kontrol. Prestasi adalah tongkat pengukur untuk Border Collies, memberi mereka kegembiraan dan kepuasan. Mereka sangat kompeten dan menginginkan pengaruh dalam segala situasi untuk memastikan segala sesuatunya dilakukan dengan benar. Sikap saya-bisa-melakukan-apa saja-saya-menetapkan-pikiran-saya-untuk-melakukan tampaknya dibangun di dalamnya.\n" +
                        "\n" +
                        "Termotivasi oleh alasan dan logika daripada perasaan, Border Collies berorientasi pada fakta. Mereka cenderung tetap tidak terikat secara objektif, bahkan di tengah situasi yang penuh tekanan. Border Collies sangat percaya diri dengan sikap menang dengan segala cara. Mereka adalah orang-orang yang berprestasi di hampir semua bidang, bermotivasi tinggi dan secara alami kompetitif, baik dengan orang lain maupun untuk memperbaiki rekor mereka sendiri. Mereka menikmati tantangan dan tidak pernah puas dengan yang kurang dari yang terbaik. Sangat terorganisir, analitis, dan sistematis, mereka lebih suka aturan yang masuk akal, dan mereka menghargai komunikasi yang jelas, yang membantu mereka mematuhinya. Jika mereka tidak setuju atau memahami aturan, mereka cenderung menantang orang dewasa yang menetapkan aturan. Mereka paling bahagia saat memimpin dan mengatur kelompok sebaya mereka untuk menghasilkan hasil.\n" +
                        "\n" +
                        "Anak-anak Border Collie akan menjadi pemimpin dan membutuhkan orang dewasa yang sabar yang akan membantu mereka mengembangkan kualitas kepemimpinan yang efektif. Mereka sangat puas menjadi pemimpin dan kemungkinan besar akan berada di posisi kepemimpinan untuk semua atau sebagian dari kehidupan mereka. Pengorganisasian datang secara alami kepada mereka, dan mereka adalah delegator yang sangat baik. Border Collies akan mendelegasikan, mengatur, dan mengekspresikan kemampuan kepemimpinan mereka dalam konteks keluarga. Apa tempat yang bagus untuk belajar! Namun, ketika mereka melampaui batas, beri tahu mereka. Mereka membutuhkan orang dewasa yang akan menetapkan batasan dan menyalurkan energi mereka. Border Collies akan menghormati dan senang bekerja di bawah otoritas selama mereka tahu dan mengerti apa yang diperbolehkan dan apa yang tidak diperbolehkan. Sikap Border Collies yang menyenangkan dan suka berteman bercampur dengan rasa tanggung jawab mereka membuat kombo yang kuat yang dapat secara signifikan meningkatkan dan memajukan dunia.",
                "https://www.youtube.com/watch?v=rkczkn998JI;https://www.youtube.com/watch?v=3G81qlgvPko;https://www.youtube.com/watch?v=PVTTJUBLLvQ&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=55;https://www.youtube.com/watch?v=hkilGLQHpgA&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=66;https://www.youtube.com/watch?v=enIDg17LPMM&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=72;https://www.youtube.com/watch?v=xZd3F9WQz48&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=53;https://www.youtube.com/watch?v=zCkOocQGtDU&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=73;https://www.youtube.com/watch?v=eKDbdAZO-F0;https://www.youtube.com/watch?v=CSo0NazM6XI&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=17;https://www.youtube.com/watch?v=Naui0ZG-Nsc&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=61;https://www.youtube.com/watch?v=k-OfuX72ww0;https://www.youtube.com/watch?v=kAo4-2UzgPo;https://www.youtube.com/watch?v=eKDbdAZO-F0;https://www.youtube.com/watch?v=Pb059iwcyUA&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=1;https://www.youtube.com/watch?v=iFDlLz50AWE&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=11;https://www.youtube.com/watch?v=ag92tlMNITg&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=41",
                "Border Collie",
                "image url"
            )
        )

        personalities.add(
            PersonalityEntity(
                13,
                "ENTP",
                0f,
                "Energetik dan Penuh Ide",
                "Perpaduan yang sangat baik antara keramahan dan kemandirian. Berfokus pada ide dan kemungkinan kreatif, dan menghargai perspektif yang berbeda. Cinta variasi dan perubahan, dengan kemampuan untuk menyelesaikan tugas secara mandiri.",
                "Anda tahu anak-anak yang berbicara dengan telinga Anda dan menantang semua yang Anda katakan?! Nah, inilah mereka. Selamat datang di dunia Parrot yang suka berteman, banyak bicara, dan kreatif!\n" +
                        "\n" +
                        "Mereka adalah ekstrovert yang suka berbicara dan mempertanyakan segalanya - termasuk aturan. Mereka perlu memahami alasan di balik aturan untuk mematuhinya. Mereka menyukai variasi, perubahan, dan menyambut pengalaman baru tanpa syarat. Lebih dari anak-anak lainnya, Parrots cenderung memiliki keseimbangan sosialisasi dan kemandirian yang baik untuk mengejar proyek kreatif mereka. Sebagai skeptis yang ingin tahu, Parrots dapat menghabiskan waktu berjam-jam sendiri untuk menjelajahi, bermain, dan mencari tahu, namun mereka selalu siap untuk pesta. Mereka ramah dan percaya diri dengan siapa mereka, bersedia mengambil risiko dan secara teratur mencari tantangan baru. Burung beo paling bahagia saat berpartisipasi dalam kegiatan baru dengan orang lain atau berbicara. Mereka menikmati percakapan cerdas untuk kesempatan mendapatkan berbagai perspektif.\n" +
                        "\n" +
                        "Anak-anak burung beo benar-benar penasaran. Mereka menginginkan kebebasan dan fleksibilitas untuk mengeksplorasi ide-ide kreatif mereka dan menggunakan energi tinggi mereka untuk mewujudkan ide-ide. Burung beo sangat investigasi dan antusias dengan proyek kreatif apa pun yang mereka kejar. Mereka cenderung memiliki sikap \"Saya-bisa-melakukan-apa saja-saya-menetapkan-pikiran-saya\", yang memungkinkan mereka mengatasi tantangan yang cenderung ditakuti oleh anak-anak lain. Karena kepribadian mereka yang persuasif dan kemauan untuk menantang, mereka cenderung menjadi pemimpin di antara teman-teman mereka. Mereka lebih suka berada di luar menjelajahi alam atau bermain olahraga daripada duduk di dalam kelas. Mereka merasa sulit untuk duduk diam karena energi mereka yang tinggi dan kebutuhan mereka akan perubahan serta pengalaman kehidupan nyata. Anak-anak ini harus memiliki ruang untuk eksplorasi, observasi, dan kesempatan untuk berbicara melalui segalanya.\n" +
                        "\n" +
                        "Mereka lebih suka dunia mereka selalu berubah, fleksibel, dan menyenangkan. Burung beo menyambut perubahan karena fokus mereka adalah pada kemungkinan. Mereka bertanya pada diri sendiri pertanyaan seperti, hal baru apa yang bisa saya pelajari dari ini? Sebagai pencari sensasi, mereka perlu mengalami risiko dan membuat kesalahan untuk mempelajari kemungkinan lain yang muncul. Otak mereka seperti taman bermain ide yang melihat potensi di mana-mana dan membawa mereka ke kemungkinan dan petualangan tanpa akhir. Mereka membutuhkan orang dewasa yang tahu bagaimana menyalurkan energi tinggi mereka tanpa menekan ide-ide kreatif mereka. Keingintahuan dan kreativitas burung beo, bercampur dengan kepercayaan diri mereka, membuat kombo yang kuat yang secara signifikan dapat membuat dunia menjadi tempat yang lebih baik (dan lebih hidup!)",
                "https://www.youtube.com/watch?v=rkczkn998JI;https://www.youtube.com/watch?v=3G81qlgvPko;https://www.youtube.com/watch?v=kAo4-2UzgPo;https://www.youtube.com/watch?v=eKDbdAZO-F0;https://www.youtube.com/watch?v=Pb059iwcyUA&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=1;https://www.youtube.com/watch?v=iFDlLz50AWE&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=11;https://www.youtube.com/watch?v=ag92tlMNITg&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=41;https://www.youtube.com/watch?v=xZd3F9WQz48&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=53;https://www.youtube.com/watch?v=zCkOocQGtDU&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=73;https://www.youtube.com/watch?v=bhlUJvj7sZw&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=16;https://www.youtube.com/watch?v=NK0ojZTsKxw&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=29;https://www.youtube.com/watch?v=0MANp5bqy7w&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=33;https://www.youtube.com/watch?v=FgdKD9owv7E&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=7;https://www.youtube.com/watch?v=iFDlLz50AWE&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=12;https://www.youtube.com/watch?v=i1UfefPfa8I&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=65",
                "Parrot",
                "image url"
            )
        )

        personalities.add(
            PersonalityEntity(
                14,
                "ENFP",
                0f,
                "Energetik dan Penuh Ide",
                "Perpaduan yang sangat baik antara keramahan dan kemandirian. Berfokus pada ide dan kemungkinan kreatif, dan menghargai perspektif yang berbeda. Cinta variasi dan perubahan, dengan kemampuan untuk menyelesaikan tugas secara mandiri.",
                "Anda tahu anak-anak yang berbicara dengan telinga Anda dan menantang semua yang Anda katakan?! Nah, inilah mereka. Selamat datang di dunia Parrot yang suka berteman, banyak bicara, dan kreatif!\n" +
                        "\n" +
                        "Mereka adalah ekstrovert yang suka berbicara dan mempertanyakan segalanya - termasuk aturan. Mereka perlu memahami alasan di balik aturan untuk mematuhinya. Mereka menyukai variasi, perubahan, dan menyambut pengalaman baru tanpa syarat. Lebih dari anak-anak lainnya, Parrots cenderung memiliki keseimbangan sosialisasi dan kemandirian yang baik untuk mengejar proyek kreatif mereka. Sebagai skeptis yang ingin tahu, Parrots dapat menghabiskan waktu berjam-jam sendiri untuk menjelajahi, bermain, dan mencari tahu, namun mereka selalu siap untuk pesta. Mereka ramah dan percaya diri dengan siapa mereka, bersedia mengambil risiko dan secara teratur mencari tantangan baru. Burung beo paling bahagia saat berpartisipasi dalam kegiatan baru dengan orang lain atau berbicara. Mereka menikmati percakapan cerdas untuk kesempatan mendapatkan berbagai perspektif.\n" +
                        "\n" +
                        "Anak-anak burung beo benar-benar penasaran. Mereka menginginkan kebebasan dan fleksibilitas untuk mengeksplorasi ide-ide kreatif mereka dan menggunakan energi tinggi mereka untuk mewujudkan ide-ide. Burung beo sangat investigasi dan antusias dengan proyek kreatif apa pun yang mereka kejar. Mereka cenderung memiliki sikap \"Saya-bisa-melakukan-apa saja-saya-menetapkan-pikiran-saya\", yang memungkinkan mereka mengatasi tantangan yang cenderung ditakuti oleh anak-anak lain. Karena kepribadian mereka yang persuasif dan kemauan untuk menantang, mereka cenderung menjadi pemimpin di antara teman-teman mereka. Mereka lebih suka berada di luar menjelajahi alam atau bermain olahraga daripada duduk di dalam kelas. Mereka merasa sulit untuk duduk diam karena energi mereka yang tinggi dan kebutuhan mereka akan perubahan serta pengalaman kehidupan nyata. Anak-anak ini harus memiliki ruang untuk eksplorasi, observasi, dan kesempatan untuk berbicara melalui segalanya.\n" +
                        "\n" +
                        "Mereka lebih suka dunia mereka selalu berubah, fleksibel, dan menyenangkan. Burung beo menyambut perubahan karena fokus mereka adalah pada kemungkinan. Mereka bertanya pada diri sendiri pertanyaan seperti, hal baru apa yang bisa saya pelajari dari ini? Sebagai pencari sensasi, mereka perlu mengalami risiko dan membuat kesalahan untuk mempelajari kemungkinan lain yang muncul. Otak mereka seperti taman bermain ide yang melihat potensi di mana-mana dan membawa mereka ke kemungkinan dan petualangan tanpa akhir. Mereka membutuhkan orang dewasa yang tahu bagaimana menyalurkan energi tinggi mereka tanpa menekan ide-ide kreatif mereka. Keingintahuan dan kreativitas burung beo, bercampur dengan kepercayaan diri mereka, membuat kombo yang kuat yang secara signifikan dapat membuat dunia menjadi tempat yang lebih baik (dan lebih hidup!)",
                "https://www.youtube.com/watch?v=rkczkn998JI;https://www.youtube.com/watch?v=3G81qlgvPko;https://www.youtube.com/watch?v=RkNdYAP5mwg&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=30;https://www.youtube.com/watch?v=64fLmIWHtT4&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=31;https://www.youtube.com/watch?v=2Oazci7VrNU&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=4;https://www.youtube.com/watch?v=KbiskP6M5P8&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=13;https://www.youtube.com/watch?v=mF-2ihX6lFU&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=19;https://www.youtube.com/watch?v=mSrIydtzo6Q&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=38",
                "Parrot",
                "image url"
            )
        )

        personalities.add(
            PersonalityEntity(
                15,
                "ENFJ",
                0f,
                "Ramah, Pemikir, dan Pecinta Sesama",
                "Ramah dan terorganisir. Paling bahagia ketika membantu orang lain, merencanakan acara sosial atau berpartisipasi dalam kegiatan yang melibatkan orang - SEMUA orang. Banyak cinta untuk keluarga dan empati untuk orang lain.",
                "Selamat datang di dunia Gajah yang ramah, harmonis, dan berorientasi keluarga! Gajah memiliki preferensi untuk ekstroversi dan menyenangkan berada di sekitar. Sosialisasi sangat penting bagi anak-anak ini, karena dunia mereka berfokus pada orang lain, dan mereka memandang semua orang sebagai teman potensial. Mereka ramah dan terorganisir dengan banyak cinta dan empati untuk orang lain. Mereka peka terhadap kebutuhan orang lain. Mereka peduli dengan orang lain; mereka ingin membantu mereka, mendorong mereka, dan membantu mereka dalam memecahkan masalah mereka. Mereka adalah anak-anak yang akan merencanakan acara sosial atau menjadi yang pertama berpartisipasi dalam kegiatan yang melibatkan orang – SEMUA orang. Gajah secara alami bertanggung jawab dan mencoba yang terbaik untuk melakukan hal yang benar dalam setiap situasi.\n" +
                        "\n" +
                        "Dunia mereka terorganisir, metodis, dan berorientasi pada tujuan. Mereka menikmati perencanaan, memimpin, atau berpartisipasi dalam berbagai kegiatan sosial. Karena hubungan adalah hal yang paling penting bagi mereka, konflik dan pertengkaran cenderung membuat mereka kesal, menyebabkan kecemasan dan kesusahan yang luar biasa. Gajah cenderung menjadi orang yang menyenangkan dan membutuhkan orang dewasa yang dapat mencontoh bagaimana menavigasi secara sehat melalui konflik. Gajah secara alami berempati dan cenderung membuat pengorbanan pribadi untuk kesejahteraan orang lain. Kadang-kadang, karakteristik ini luar biasa; namun, mereka juga perlu diajari cara menggunakan suara mereka, menetapkan batasan, dan bersikap tegas dengan hormat. Anak ini akan berkembang dengan komunikasi keluarga yang sehat, banyak pujian, dan rasa aman secara emosional. Cinta dan kepedulian mereka yang murah hati terhadap orang-orang, bercampur dengan tanggung jawab sosial mereka, membuat kombinasi yang kuat yang secara signifikan dapat membuat dunia menjadi tempat yang lebih baik (dan lebih harmonis).",
                "https://www.youtube.com/watch?v=rkczkn998JI;https://www.youtube.com/watch?v=3G81qlgvPko;https://www.youtube.com/watch?v=2Oazci7VrNU&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=5;https://www.youtube.com/watch?v=NK0ojZTsKxw&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=30;https://www.youtube.com/watch?v=mSrIydtzo6Q&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=39;https://www.youtube.com/watch?v=Naui0ZG-Nsc&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=62;https://www.youtube.com/watch?v=9-4GqSZ7VXQ&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=63",
                "Elephant",
                "image url"
            )
        )

        personalities.add(
            PersonalityEntity(
                16,
                "ESFJ",
                0f,
                "Ramah, Pemikir, dan Pecinta Sesama",
                "Ramah dan terorganisir. Paling bahagia ketika membantu orang lain, merencanakan acara sosial atau berpartisipasi dalam kegiatan yang melibatkan orang - SEMUA orang. Banyak cinta untuk keluarga dan empati untuk orang lain.",
                "Selamat datang di dunia Gajah yang ramah, harmonis, dan berorientasi keluarga! Gajah memiliki preferensi untuk ekstroversi dan menyenangkan berada di sekitar. Sosialisasi sangat penting bagi anak-anak ini, karena dunia mereka berfokus pada orang lain, dan mereka memandang semua orang sebagai teman potensial. Mereka ramah dan terorganisir dengan banyak cinta dan empati untuk orang lain. Mereka peka terhadap kebutuhan orang lain. Mereka peduli dengan orang lain; mereka ingin membantu mereka, mendorong mereka, dan membantu mereka dalam memecahkan masalah mereka. Mereka adalah anak-anak yang akan merencanakan acara sosial atau menjadi yang pertama berpartisipasi dalam kegiatan yang melibatkan orang – SEMUA orang. Gajah secara alami bertanggung jawab dan mencoba yang terbaik untuk melakukan hal yang benar dalam setiap situasi.\n" +
                        "\n" +
                        "Dunia mereka terorganisir, metodis, dan berorientasi pada tujuan. Mereka menikmati perencanaan, memimpin, atau berpartisipasi dalam berbagai kegiatan sosial. Karena hubungan adalah hal yang paling penting bagi mereka, konflik dan pertengkaran cenderung membuat mereka kesal, menyebabkan kecemasan dan kesusahan yang luar biasa. Gajah cenderung menjadi orang yang menyenangkan dan membutuhkan orang dewasa yang dapat mencontoh bagaimana menavigasi secara sehat melalui konflik. Gajah secara alami berempati dan cenderung membuat pengorbanan pribadi untuk kesejahteraan orang lain. Kadang-kadang, karakteristik ini luar biasa; namun, mereka juga perlu diajari cara menggunakan suara mereka, menetapkan batasan, dan bersikap tegas dengan hormat. Anak ini akan berkembang dengan komunikasi keluarga yang sehat, banyak pujian, dan rasa aman secara emosional. Cinta dan kepedulian mereka yang murah hati terhadap orang-orang, bercampur dengan tanggung jawab sosial mereka, membuat kombinasi yang kuat yang secara signifikan dapat membuat dunia menjadi tempat yang lebih baik (dan lebih harmonis).",
                "https://www.youtube.com/watch?v=rkczkn998JI;https://www.youtube.com/watch?v=3G81qlgvPko;https://www.youtube.com/watch?v=RkNdYAP5mwg&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=30;https://www.youtube.com/watch?v=64fLmIWHtT4&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=31;https://www.youtube.com/watch?v=2Oazci7VrNU&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=4;https://www.youtube.com/watch?v=KbiskP6M5P8&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=13;https://www.youtube.com/watch?v=mF-2ihX6lFU&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=19;https://www.youtube.com/watch?v=mSrIydtzo6Q&list=PL_DANuu1-w9pTPqXgaATYxvK7paI1IUjh&index=38",
                "Elephant",
                "image url"
            )
        )

        return personalities
    }
}